### ISSUE TITLE
CLR Access violation on GetCredentials after saving them with SaveCredentials

### ISSUE THREAD

**Issue by nguillermin** [AdysTech/CredentialManager#9] opened 2017-12-21 14:19 UTC
Fairly simple, this code

    Credential = CredentialManager.GetCredentials(CredentialTarget);

Potential error message:

    Exception thrown: 'System.ArgumentOutOfRangeException' in mscorlib.dll

Also this:

```
Exception thrown at 0x73BDFEC2 (clr.dll) in OdinSyncD.exe: 0xC0000005: Access violation reading location 0x00AF0000.
The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.
Managed Debugging Assistant 'FatalExecutionEngineError' 
The runtime has encountered a fatal error. The address of the error was at 0x73bdfec2, on thread 0x313c. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.
```

This happens whether or not I save the credentials myself or use Adystech. It only seems to happen for certain username/passwords pairings and not others.

I also sometimes get a `Error: 0 : Not a valid Win32 FileTime. Parameter name: fileTime`

**Comment by mvadu** [comment] 2017-12-22 12:29
@nguillermin could you please give me full callstack when this exception occurs? Also your CLR & windows version please.

**Comment by mvadu** [comment] 2018-06-25 02:39
Closing due to lack of more information.

**Comment by zybexXL** [comment] 2018-06-28 22:28
We're also seeing this now. It happens with longer usernames, and I think the issue is here:
https://github.com/AdysTech/CredentialManager/blob/a650bb2e23f37000845fa82f0ca17c264973542a/AdysTech.CredentialManager/CredentialManager.cs#L259

The StringBuilders given as buffers are not initialized with a Capacity, so they have the default capacity of 16 bytes - that's just enough for 8 unicode chars. If the Username is longer than that, we *might* get an Access Denied error, depending on current stack layout.

The fix is simply to initialize StringBuilder with 2*user.Length capacity.

Quoting:
_To solve this problem (since many of the Win32 APIs expect string buffers) in the full .NET Framework, you can, instead, pass a System.Text.StringBuilder object; a pointer will be passed by the marshaler into the unmanaged function that can be manipulated. The only caveat is that the StringBuilder must be allocated enough space for the return value, or the text will overflow, causing an exception to be thrown by P/Invoke._

**Comment by mvadu** [comment] 2018-07-05 12:32
Spot ON!! The API handles small buffer sizes, but the problem here was taht I was wrongly passing `int.MazSize` as buffer size and not the actual size. 

Fixing that to use actual buffer sizes gives the expected `InsufficientBuffer` error. 

```
var ret1 = NativeCode.CredUIParseUserName(user, userBuilder, userBuilder.Capacity, domainBuilder, domainBuilder.Capacity);

cred.UserName
"AdysTech.com\\ZYYM3ufm3kFY9ZJZUAqYFQfzxcRc9rzdYxUwqEhBqqdrHttrhcvn"
cred.UserName.Length
65
ret1
InsufficientBuffer
```

**Closed** 2018-07-05 12:47 UTC
